### ISSUE TITLE
[SUGGESTION] Allow specification of all blocks/entities

### ISSUE THREAD

**Issue by SirPenguini** [jaqobb-mineground/rewardable-activities#8]
E.g.
break:
#block type
 *:

or
entity:
  kill:
    #entity type
    *:

etc.

**Comment by jaqobb** [comment]
Implementing such functionality would require a significant amount of time due to the existence of various materials that are not blocks and entities that cannot be found in the world. For the plugin to remain as efficient as possible, it would necessitate the creation of an internal list of potential blocks and entities, which would need to be maintained for every new Minecraft version.

If a pull request were to be made adding that functionality, I would be willing to contribute to its ongoing maintenance.

For the time being, I am closing this issue.
